listener:
  slotName: backup_slot
  refreshConnection: 30s
  heartbeatInterval: 10s
  filter:
    tables:
      trades:
        - insert
      users:
        - insert
  topicsMap:
    public_users: 'accounts'
    public_trades: 'transactions'
logger:
  caller: false
  level: info
  format: json
database:
  host: postgres-db
  port: 5432
  name: backup
  user: postgres
  password: 123123123
  debug: true
publisher:
  type: nats
  address: nats://broker:4222
  topic: 'wal_listener'
  topicPrefix: ''
